---
- name: Configurer le serveur web Nginx
  hosts: all
  become: yes
  tasks:

    - name: Installation de nginx via dnf en désactivant le dépôt specifique
      ansible.builtin.dnf:
        name: nginx
        state: present
        # Le paramètre 'disable_repo' est l'équivalent de '--disablerepo' pour dnf/yum.
        disablerepo: 
          - google-compute-engine
          - google-cloud-sdk
          - rhui-rhel-9-for-x86_64-appstream-rhui-debug-rpms

    - name: Créer la page d'accueil personnalisée
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="fr">
          <head>
            <title>Bienvenue !</title>
            <meta charset="UTF-8">
          </head>
          <body>
            <h1>Bienvenue sur mon application</h1>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: S'assurer que le service Nginx est démarré et activé au boot
      service:
        name: nginx
        state: started
        enabled: yes
