name: Build image
run-name: Build image / ${{ inputs.machine_type }}

permissions:
  contents: 'read'
  id-token: 'write'

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'ID projet GCP'
        default: "k-ops-sandbox"
        required: true
        type: choice
        options:
          - k-ops-sandbox
      machine_type:
        description: 'image source'
        default: "rhel-9"
        required: true
        type: choice
        options:
          - rhel-9
          - rhel-8
      prefix_name:
        description: 'Prefix de nommage des images (optionnel)'
        type: string
      validate:
        description: 'Lancer les tests de validation sur l''image construite'
        type: boolean
        default: false

  workflow_call:
    inputs:
      project_id:
        default: "k-ops-sandbox"
        type: string
      machine_type:
        type: string
      validate:
        default: false
        type: boolean

env:
  repository_git: 'ansible'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAME: ${{ steps.image_name.outputs.IMAGE_NAME }}
    env:
      PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - uses: actions/checkout@v4

      - id: 'auth'
        name: Authentification GCP with workload identity federation
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/270411317394/locations/global/workloadIdentityPools/github-actions-packer/providers/github-provider'
          service_account: 'sa-buildimage@${{ inputs.project_id }}.iam.gserviceaccount.com'
          create_credentials_file: true
          token_format: 'access_token'
          access_token_lifetime: '3600s'
          cleanup_credentials: true
          export_environment_variables: true

      - id: 'gcloud'
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4"

      - name: Initialize Packer
        working-directory: templates/${{ inputs.machine_type }}
        run: packer init .

      - name: Build image
        id: build
        working-directory: templates/${{ inputs.machine_type }}
        run: |
            packer build -var project_id=${{ inputs.project_id }} \
            ${{ inputs.prefix_name != '' && format('-var "prefix_name={0}"', inputs.prefix_name) || '' }} \
            .

      - name: Install jq
        run: |
          sudo apt-get install jq -y

      - name: Get image name from Packer manifest
        id: image_name
        working-directory: templates/${{ inputs.machine_type }}
        run: |
          IMAGE_NAME=$(cat manifest.json | jq -r '.builds[0].custom_data.image_name')
          echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "IMAGE_NAME=$IMAGE_NAME"

  validate:
    needs: build
    if: ${{ inputs.validate == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: Authentification GCP with workload identity federation
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/270411317394/locations/global/workloadIdentityPools/github-actions-packer/providers/github-provider'
          service_account: 'sa-buildimage@${{ inputs.project_id }}.iam.gserviceaccount.com'

      - id: 'gcloud'
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Generate SSH key
        run: |
          ssh-keygen -t rsa -f ./gcp-ssh-key -N "" -C "gcp-user"
          chmod 400 ./gcp-ssh-key
          cat ./gcp-ssh-key.pub

      - name: Create GCP Instance
        run: |
          # Lire la clé publique pour l'injecter dans les métadonnées
          PUB_KEY=$(cat ./gcp-ssh-key.pub)

          gcloud compute instances create ${{ env.GCP_INSTANCE_NAME }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --zone=${{ env.GCP_ZONE }} \
            --machine-type=e2-micro \
            --image-family=debian-11 \
            --image-project=debian-cloud \
            --boot-disk-size=10GB \
            --tags=allow-ssh \ # Important pour le pare-feu
            --metadata="ssh-keys=gcp-user:$PUB_KEY" # Injecte la clé pour l'utilisateur 'gcp-user'
          
          echo "Instance créée."

      - name: Get Instance External IP
        id: get_ip # Donne un ID à cette étape pour réutiliser sa sortie
        run: |
          IP_ADDRESS=$(gcloud compute instances describe ${{ env.GCP_INSTANCE_NAME }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --zone=${{ env.GCP_ZONE }} \
            --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          
          echo "Instance IP: $IP_ADDRESS"
          echo "INSTANCE_IP=$IP_ADDRESS" >> $GITHUB_ENV # Stocke l'IP dans les variables d'env du job

      # 7. Attendre que le port SSH soit prêt
      - name: Wait for SSH
        run: |
          echo "Waiting for SSH connection to ${{ env.INSTANCE_IP }}..."
          # Boucle simple pour attendre que le port 22 soit ouvert
          # -o StrictHostKeyChecking=no évite la demande de confirmation
          until ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i ./gcp-ssh-key gcp-user@${{ env.INSTANCE_IP }} "echo 'SSH is up'"
          do
            echo "SSH not ready yet, retrying..."
            sleep 5
          done
          echo "SSH connection established."

      # 8. Lancer les tests Testinfra
      - name: Run Testinfra tests
        run: |
          pytest \
            --hosts="ssh://gcp-user@${{ env.INSTANCE_IP }}" \
            --ssh-identity-file=./gcp-ssh-key \
            --ssh-extra-args="-o StrictHostKeyChecking=no" \
            tests/

      # 9. Nettoyage (s'exécute toujours, même si les tests échouent)
      - name: Delete GCP Instance
        if: always() # Garantit le nettoyage
        run: |
          echo "Deleting instance ${{ env.GCP_INSTANCE_NAME }}..."
          gcloud compute instances delete ${{ env.GCP_INSTANCE_NAME }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --zone=${{ env.GCP_ZONE }} \
            --quiet