---
port:
  tcp:80:
    listening: true
    ip:
      - 0.0.0.0
      - '::'

service:
  nginx:
    enabled: true
    running: true

package:
  nginx:
    installed: true

file:
  /usr/share/nginx/html/index.html:
    exists: true
    owner: nginx
    group: nginx
    mode: "0755"
    contains:
      - "<h1>Bienvenue sur mon application</h1>"